#!/bin/bash

# Build script to scan projects directory and generate page list
# This scans all XML files and extracts surface xml:id to create page list

OUTPUT_FILE="src/generated_pages.rs"

echo "// Auto-generated by build_page_list.sh" > "$OUTPUT_FILE"
echo "// Do not edit manually" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "pub fn get_available_pages() -> Vec<(String, String)> {" >> "$OUTPUT_FILE"
echo "    vec![" >> "$OUTPUT_FILE"

# Find all XML files in projects directory
find projects -name "*.xml" -type f | sort | while read -r xmlfile; do
    # Extract the surface xml:id
    surface_id=$(grep -oP 'surface[^>]+xml:id="\K[^"]+' "$xmlfile" 2>/dev/null | head -1)

    if [ -n "$surface_id" ]; then
        # Get the project name (directory name)
        project=$(echo "$xmlfile" | cut -d'/' -f2)

        # Get the filename without path and extension
        filename=$(basename "$xmlfile" .xml)

        # Extract page type (dip or trad)
        if [[ "$filename" == *"_dip"* ]]; then
            page_type="Diplomatic"
        elif [[ "$filename" == *"_trad"* ]]; then
            page_type="Translation"
        else
            page_type="Edition"
        fi

        echo "        (\"$surface_id\".to_string(), \"$project - Page $surface_id ($page_type)\".to_string())," >> "$OUTPUT_FILE"
    fi
done

# Get unique page IDs (since multiple XMLs can reference same page)
echo "    ]" >> "$OUTPUT_FILE"
echo "}" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Generate function to get unique pages
echo "pub fn get_unique_pages() -> Vec<String> {" >> "$OUTPUT_FILE"
echo "    let mut pages = vec![];" >> "$OUTPUT_FILE"

find projects -name "*.xml" -type f | while read -r xmlfile; do
    surface_id=$(grep -oP 'surface[^>]+xml:id="\K[^"]+' "$xmlfile" 2>/dev/null | head -1)
    if [ -n "$surface_id" ]; then
        echo "$surface_id"
    fi
done | sort -u | while read -r page_id; do
    echo "    pages.push(\"$page_id\".to_string());" >> "$OUTPUT_FILE"
done

echo "    pages" >> "$OUTPUT_FILE"
echo "}" >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE with page list from projects directory"
