// Auto-generated by build_page_list.sh
// Do not edit manually

pub fn get_available_pages() -> Vec<(String, String)> {
    vec![
        ("p1".to_string(), "PGM-XIII - Page p1 (Diplomatic)".to_string()),
        ("p1".to_string(), "PGM-XIII - Page p1 (Translation)".to_string()),
        ("p2".to_string(), "PGM-XIII - Page p2 (Diplomatic)".to_string()),
        ("p2".to_string(), "PGM-XIII - Page p2 (Translation)".to_string()),
        ("p3".to_string(), "PGM-XIII - Page p3 (Diplomatic)".to_string()),
        ("p3".to_string(), "PGM-XIII - Page p3 (Translation)".to_string()),
    ]
}

pub fn get_unique_pages() -> Vec<String> {
    let mut pages = vec![];
    pages.push("p1".to_string());
    pages.push("p2".to_string());
    pages.push("p3".to_string());
    pages
}
